# can setup an image for all steps with no image defined within it
image: node:lts

# define stages and order of execution
stages:
    - build
    - test
    - deploy review
    - deploy staging
    - deploy production
    - production tests

cache: # usgin cache here, will cache globally, if inside a step, would cache only that step
    key: ${CI_COMMI_REF_SLUG} # refer to the current branch, and this download will available for the  job level, or global
    paths:
      - node_modules/ # path to cache the downloads

variables:
    STAGING_DOMAIN: cassiobolba-staging.surge.sh
    PRODUCTION_DOMAIN: cassiobolba.surge.sh

build website:
    # change from standard docker image to a node image
    # image: node 
    # tell which stage it runs
    stage: build
    only:
        - master
        - merge_requests
        - branches 
    script:
        # install all dependencies for node
        - npm install
        # install the gatsby web client
        - npm install -g gatsby-cli 
        # build the web
        - gatsby build
        # create the %%VERSION%% var inside the file you want te variable to be replaced
        # Then use sed to locate and replace the %%VERSION%% in the file for the env var we called on echo
        # -i is to replace text in same file not create a new,
        - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
    # add artifacts to keep the website files in a folder to be accessed later
    artifacts:
        paths:
            - ./public

# step to deploy a review env and custom names based on the branch
deploy review:
    stage: deploy review
    only: 
        - merge_request
    environment:
        # env name and url based on commit name and on env slug, to be dynamic
        name: review/$CI_COMMIT_REF_NAME 
        url: http://cassiobolba-$CI_ENVIRONMENT_SLUG.surge.sh
        on_stop: stop review
    script: 
        - npm install --global surge
        # domain also dynamic to create a page based on the current env / branch
        - surge --project ./public --domain cassiobolba-$CI_ENVIRONMENT_SLUG.surge.sh

# step to enable the destruction of staging environment after merge
stop review:
    stage: deploy review
    # define git strategy to none and it avoid that in case the branch is already deleted, it wont clone the branch to perform the actions, which would be default strategy
    variables:
        GIT_STRATEGY: none
    environment:
        name: review/$CI_COMMIT_REF_NAME 
        action: stop
    script: 
        - npm install --global surge
        # here we use the surge command to delete the surge enviroment
        - surge teardown cassiobolba-$CI_ENVIRONMENT_SLUG.surge.sh
    when: manual
    only: 
        - merge_request

test artifact:
    # use alpine image because it is very small and fast
    image: alpine
    stage: test
    only:
        - master
        - merge_requests
        - branches 
    script:
        - grep -q "Gatsby" ./public/index.html

# test the website server gatsby provides
test website:
    # image: node
    stage: test
    only:
        - master
        - merge_requests
        - branches 
    script:
        # use enviroment variables on the pipeline content (web site this case)
        # list of variables https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
        - echo $CI_COMMIT_SHORT_SHA
        - npm install
        - npm install -g gatsby-cli
        # after install gatsby in this job, initialize the server and use & to move to next command
        # because initializing a server block the terminal to that action
        - gatsby serve &
        # increasing time
        - sleep 7
        # curl download the content and look for the word gatsby in the page
        - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"


# to make this work, you should have installed node in your machine, then npm install surge in the folder with the web site files
# after create the key for surge and regitered both to Git environment variables
deploy production:
    stage: deploy production
    # only is to specify policies where to run the step
    only: 
        - master
    environment:
        name: production
        url: http://$PRODUCTION_DOMAIN
    script: 
        - npm install --global surge
        - surge --project ./public --domain $PRODUCTION_DOMAIN

deploy staging:
    stage: deploy staging
    #enviroment label is used to define to which env it will be deployed
    only: 
        - master
        - branches 
    environment: 
        name: staging
        url: http://$STAGING_DOMAIN
    script: 
        - npm install --global surge
        - surge --project ./public --domain $STAGING_DOMAIN

production tests:
    image: alpine
    stage: production tests
    only: 
        - master
    script:
        - apk add --no-cache curl
        - curl -s "$PRODUCTION_DOMAIN" | grep -q "Congratulations"
        - curl -s "$PRODUCTION_DOMAIN" | grep -q "$CI_COMMIT_SHORT_SHA"
