CREATE OR REPLACE SCHEMA FILE_FORMATS;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT
	FIELD_DELIMITER = '\t'
    TYPE = CSV
    --SKIP_HEADER=1
    ;

DESC FILE FORMAT FILE_FORMATS.CSV_TAB_FMT;

LIST @MANAGE_DB.EXTERNAL_STAGES.GDELT_EVENTS/events/ ;

COPY INTO GDELT.EVENTS.EVENTS_FULL
	FROM @MANAGE_DB.EXTERNAL_STAGES.GDELT_EVENTS/events/20130922.export.csv
    file_format = MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT
;