-- CRIAR STAGE > CARREGAR DADOS BRUTOS > ANALISE E PARSE > CRIAR O COMANDO COPY 

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_SERIES
	URL= 's3://snowflake-series/'
    STORAGE_INTEGRATION = S3_INT;

LIST @MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_SERIES;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.JSON_FMT
    TYPE = JSON;

CREATE DATABASE MEDIAS;

CREATE SCHEMA MEDIAS.YOUTUBE;

CREATE OR REPLACE table MEDIAS.YOUTUBE.STATISTICS_RAW (
    raw_file variant);

COPY INTO MEDIAS.YOUTUBE.STATISTICS_RAW
    FROM @MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_SERIES
    file_format= MANAGE_DB.FILE_FORMATS.JSON_FMT
    files = ('youtube_data.json');

SELECT * FROM MEDIAS.YOUTUBE.STATISTICS_RAW ;
