CREATE OR REPLACE DATABASE MANAGE_DB;

USE DATABASE MANAGE_DB;
CREATE SCHEMA EXTERNAL_STAGES;

USE SCHEMA EXTERNAL_STAGES;

CREATE OR REPLACE STAGE GDELT_EVENTS
	URL = 's3://gdelt-open-data/' ;

LIST @MANAGE_DB.EXTERNAL_STAGES.GDELT_EVENTS ;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.GDELT_EVENTS ;

ALTER STAGE MANAGE_DB.EXTERNAL_STAGES.GDELT_EVENTS
	SET CREDENTIALS=(aws_key_id='cab' aws_secret_key='123')