CREATE OR REPLACE TABLE GDELT.EVENTS.EVENTS_URL AS 
SELECT 
	 $1::INT GLOBALEVENTID
    ,TO_DATE($2,'YYYYMMDD') AS SQLDATE
    ,$3 MONTHYEAR
    ,$58 SOURCEURL
FROM @MANAGE_DB.EXTERNAL_STAGES.GDELT_EVENTS/events/20190916.export.csv 
(file_format => MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT)
;

COPY INTO GDELT.EVENTS.EVENTS_URL FROM (
SELECT 
	 $1::INT GLOBALEVENTID
    ,TO_DATE($2,'YYYYMMDD') AS SQLDATE
    ,$3 MONTHYEAR
    ,$58 SOURCEURL
FROM @MANAGE_DB.EXTERNAL_STAGES.GDELT_EVENTS/events/20190917.export.csv 
(file_format => MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT)
);

