CREATE SCHEMA MANAGE_DB.PIPES;

CREATE PIPE MANAGE_DB.PIPES.JSON_PIPE
	AUTO_INGEST = TRUE
    AS
    COPY INTO MEDIAS.YOUTUBE.STATISTICS_RAW
    FROM @MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_SERIES
    file_format= MANAGE_DB.FILE_FORMATS.JSON_FMT;

DESC PIPE JSON_PIPE;

SELECT * FROM MEDIAS.YOUTUBE.STATISTICS_RAW;

TRUNCATE TABLE MEDIAS.YOUTUBE.STATISTICS_RAW;