version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "firstlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ui27hk7cis4s"
s3_prefix = "firstlambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
