/*-------------------------------------------------------------
STAGE
CRIAR STAGE > CARREGAR DADOS BRUTOS > ANALISE E PARSE > CRIAR O COMANDO COPY 
-------------------------------------------------------------*/

USE DATABASE MANAGE_DB;

CREATE SCHEMA IF NOT EXISTS EXTERNAL_STAGES;

USE SCHEMA EXTERNAL_STAGES;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_WORKSHOP
	URL= 's3://snowflake-ws/'
    --FILE_FORMAT = (  TYPE = CSV | JSON | AVRO | ORC | PARQUET | XML )
    --CREDENTIALS = (  AWS_KEY_ID = '' AWS_SECRET_KEY = '' )
    --ENCRYPTION =  (  TYPE = 'AWS_CSE'  MASTER_KEY = '' )
    --COPY_OPTIONS = ( )
    --TAG = ''
    STORAGE_INTEGRATION = AWS_S3_INT;

LIST @MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_WORKSHOP;

DESC STAGE SNOWFLAKE_WORKSHOP;

SHOW STAGES LIKE '%WORKSHOP%';


/*-------------------------------------------------------------
FILE FORMAT
-------------------------------------------------------------*/

CREATE SCHEMA FILE_FORMATS;
USE SCHEMA FILE_FORMATS;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.JSON_FMT
     TYPE = JSON
     -- COMPRESSION = AUTO | GZIP | BZ2 | BROTLI | ZSTD | DEFLATE | RAW_DEFLATE | NONE
     -- DATE_FORMAT = '' | AUTO
     -- TIME_FORMAT = '' | AUTO
     -- TIMESTAMP_FORMAT = '' | AUTO
     -- BINARY_FORMAT = HEX | BASE64 | UTF8
     TRIM_SPACE = TRUE
     -- NULL_IF = ( '' )
     -- FILE_EXTENSION = ''
     -- ENABLE_OCTAL = TRUE | FALSE
     ALLOW_DUPLICATE = TRUE
     -- STRIP_OUTER_ARRAY = TRUE | FALSE
     -- STRIP_NULL_VALUES = TRUE | FALSE
     REPLACE_INVALID_CHARACTERS = TRUE
     -- IGNORE_UTF8_ERRORS = TRUE | FALSE
     -- SKIP_BYTE_ORDER_MARK = TRUE | FALSE
     
     -- TYPE = PARQUET
     -- COMPRESSION = AUTO | LZO | SNAPPY | NONE
     -- SNAPPY_COMPRESSION = TRUE | FALSE
     -- BINARY_AS_TEXT = TRUE | FALSE
     -- TRIM_SPACE = TRUE | FALSE
     -- NULL_IF = ( '' )
    ;

SHOW FILE FORMATS;

DESC FILE FORMAT JSON_FMT;



