SELECT * FROM @MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_WORKSHOP
(file_format => MANAGE_DB.FILE_FORMATS.JSON_FMT);

CREATE DATABASE MEDIAS;

CREATE SCHEMA MEDIAS.YOUTUBE;

CREATE OR REPLACE TABLE MEDIAS.YOUTUBE.RAW (
    RAW_FILE VARIANT);

COPY INTO MEDIAS.YOUTUBE.RAW -- ( RAW_FILE )
    FROM @MANAGE_DB.EXTERNAL_STAGES.SNOWFLAKE_WORKSHOP
    FILE_FORMAT= MANAGE_DB.FILE_FORMATS.JSON_FMT
    -- PATTERN = '.*error.json'
    -- FILES = ('youtube_data.json')
    ON_ERROR = SKIP_FILE --CONTINUE | SKIP_FILE | SKIP_FILE_<num> | 'SKIP_FILE_<num>%' | ABORT_STATEMENT
    -- SIZE_LIMIT = <num>
    -- PURGE = TRUE
    -- RETURN_FAILED_ONLY = TRUE | FALSE
    -- MATCH_BY_COLUMN_NAME = CASE_SENSITIVE | CASE_INSENSITIVE | NONE
    -- ENFORCE_LENGTH = TRUE | FALSE
    -- TRUNCATECOLUMNS = TRUE | FALSE
    -- FORCE = TRUE
    ;

SELECT * FROM MEDIAS.YOUTUBE.RAW ;

TRUNCATE TABLE MEDIAS.YOUTUBE.RAW ;


